# EXERCISE 4.10 (A)
# Coding Etiquette & Excel Reporting

#### Table of Content

1. Importing Libraries
2. Dataframe
3. Checking the Dataframe
4. Following Exercise 4.10

## 1. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os

## 2. Dataframe

In [2]:
path = r'/Users/charliegehant/Dropbox/4. Career Foundry/Achievement 4 - Python Fundamentals for Data Analysts/02-2022 Instacart Basket Analysis'

In [3]:
path

'/Users/charliegehant/Dropbox/4. Career Foundry/Achievement 4 - Python Fundamentals for Data Analysts/02-2022 Instacart Basket Analysis'

In [5]:
# Importing dataframe 'orders.csv'

df = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'orders.csv'))

## 3. Checking the Dataframe

In [6]:
df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [7]:
df.shape

(3421083, 7)

## 4. Following Exercise 4.10

In [9]:
# Crosstab = a sort of Pivot Table, but for Python!

crosstab = pd.crosstab(df['days_since_prior_order'], df['order_number'], dropna = False)

In [10]:
# Copy/Paste the crosstabs result to clipboard, ready to be pasted in Excel

crosstab.to_clipboard()

In [12]:
# Printing the crosstab here for reference

crosstab

order_number,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
days_since_prior_order,,,,,,,,,,,,,,,,,,,,,
0.0,0,2899,2915,2964,2634,2443,2236,2101,1972,1782,...,156,154,125,151,151,153,120,144,134,137
1.0,0,4822,4613,4690,4423,4047,4000,3744,3503,3358,...,397,396,373,359,366,330,356,360,339,321
2.0,0,6203,6209,6231,5789,5679,5274,5090,4914,4705,...,416,405,407,389,359,351,359,346,318,329
3.0,0,7411,7577,7414,7097,6770,6424,6078,5750,5663,...,345,287,330,294,291,292,254,221,240,223
4.0,0,8415,8476,8469,8029,7608,7092,6735,6534,6395,...,221,238,225,191,193,185,183,170,170,153
5.0,0,9216,9329,9220,8600,8228,7703,7270,6828,6563,...,142,128,105,119,119,120,100,95,82,81
6.0,0,11419,11701,11601,10771,10054,9521,8842,8527,7727,...,77,91,86,82,67,59,58,50,58,44
7.0,0,16788,16609,16341,15135,13834,13268,12452,11612,10980,...,60,56,48,56,36,37,37,41,32,35
8.0,0,10422,10304,10148,9378,8738,8068,7594,6894,6511,...,29,22,24,26,23,30,18,16,12,13
9.0,0,7053,7160,7013,6610,5993,5497,5082,4760,4404,...,12,8,14,12,8,6,7,8,7,11
10.0,0,5969,6037,5938,5376,5018,4479,4245,3844,3531,...,9,20,10,6,11,1,7,4,4,7
11.0,0,5352,5388,5325,4718,4363,4087,3767,3429,3180,...,13,13,5,7,8,6,6,1,3,7
12.0,0,5206,5357,5348,4657,4333,3954,3568,3404,2941,...,4,5,4,5,6,5,5,1,5,3
13.0,0,6098,6265,6003,5520,4855,4480,4083,3708,3408,...,8,9,5,6,5,2,3,6,6,1
14.0,0,7680,7529,7577,6951,6004,5549,4976,4563,4187,...,1,3,12,3,3,3,4,2,1,2
15.0,0,5219,5121,5225,4588,4068,3670,3384,3046,2793,...,3,3,2,1,3,2,2,1,1,1
16.0,0,3791,3794,3690,3316,2994,2665,2370,2269,2085,...,1,1,0,2,0,3,2,3,1,1
17.0,0,3131,3241,3226,2823,2546,2152,2039,1791,1662,...,0,4,1,1,1,2,2,0,2,0
18.0,0,3041,2971,2904,2660,2337,2078,1850,1730,1531,...,1,1,0,2,0,1,0,0,2,0
19.0,0,2861,2999,2877,2579,2359,2081,1872,1621,1469,...,2,0,0,0,1,2,2,0,0,1
20.0,0,3411,3380,3427,2953,2593,2355,2113,1810,1677,...,4,1,0,1,0,0,0,0,0,1
21.0,0,4258,4205,4067,3459,3263,2801,2429,2205,2021,...,0,1,1,0,1,0,0,1,0,1
22.0,0,2956,2866,2887,2504,2168,2015,1756,1619,1451,...,1,0,0,0,1,0,0,0,1,1
23.0,0,2268,2296,2204,1889,1666,1516,1282,1208,995,...,0,1,0,0,1,0,0,0,2,0
24.0,0,1875,1960,1900,1754,1496,1334,1176,996,955,...,0,0,0,0,0,0,0,0,0,0
25.0,0,1843,1879,1847,1619,1400,1198,1016,964,807,...,0,0,0,0,0,0,0,0,0,0
26.0,0,1872,1890,1760,1619,1442,1238,1084,984,843,...,0,0,0,0,1,0,0,0,0,0
27.0,0,2177,2236,2258,1994,1598,1439,1340,1138,925,...,0,0,0,0,0,0,0,0,0,0
28.0,0,2728,2760,2797,2287,2035,1745,1592,1385,1187,...,0,0,1,0,0,1,0,0,0,1
29.0,0,1986,2012,1971,1711,1489,1259,1113,984,837,...,1,0,0,0,0,0,0,0,0,0
30.0,0,47839,47130,48887,38780,31212,25290,20575,16926,14155,...,2,2,2,0,1,1,0,1,1,0

In [13]:
# Checking the data

df[['order_number', 'days_since_prior_order']].max()

order_number              100.0
days_since_prior_order     30.0
dtype: float64

In [14]:
df.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')