# TASK 4.8 (B)
# Grouping & Aggregating

#### Table of contents

1. Importing Libraries
2. Dataframes
3. Checking Dataframe
4. Task Directions
5. Final Checks
6. Exporting Dataframe

> ##### D1: Create a new notebook for this task. Be sure to import the relevant libraries, along with your ords_prods_merge dataframe, which should include your newly derived columns from the previous Exercise.

## 1. Importing Libraries

In [1]:
# Importing libraries

import pandas as pd
import numpy as np
import os

In [2]:
pd.options.display.max_rows = None

## 2. Dataframes

In [3]:
path = r'/Users/charliegehant/Dropbox/4. Career Foundry/Achievement 4 - Python Fundamentals for Data Analysts/02-2022 Instacart Basket Analysis'

In [4]:
path

'/Users/charliegehant/Dropbox/4. Career Foundry/Achievement 4 - Python Fundamentals for Data Analysts/02-2022 Instacart Basket Analysis'

In [5]:
# Importing dataframe 'orders_products_new_variables.pkl'

ords_prods_new_var = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_new_variables.pkl'))

## 3. Checking Dataframe

In [6]:
ords_prods_new_var.shape

(32435059, 20)

In [7]:
ords_prods_new_var.head()

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,opp_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,0.0,196,1,0,both,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2539329,1,prior,1,2,8,0.0,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders
2,2539329,1,prior,1,2,8,0.0,12427,3,0,both,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders
3,2539329,1,prior,1,2,8,0.0,26088,4,0,both,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders
4,2539329,1,prior,1,2,8,0.0,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders

## 4. Task Directions

> ##### D2: In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [8]:
ords_prods_new_var.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              15.457838
2.0              17.277920
3.0              17.170395
4.0              17.811403
5.0              15.215751
6.0              16.439806
7.0              17.225802
8.0              15.340650
9.0              15.895474
10.0             20.197148
11.0             16.170638
12.0             15.887671
13.0             16.583536
14.0             16.773669
15.0             16.165037
16.0             17.665606
17.0             15.694469
18.0             19.310397
19.0             17.177343
20.0             16.473447
21.0             22.902379

> ##### D3: Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

> In the subset, there were only 8 rows for 'department_id', in the entire dataframe there are 21. Moreover, when looking at the entire dataframe, the means of corresponding 'department_id' rows differs from the subset, because the subset was only incorporating some of the 'order_number' but not all of them.

> ##### D4: Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

In [9]:
# The first step is to create a new variable to base my loyalty flag on. 

ords_prods_new_var['max_order'] = ords_prods_new_var.groupby(['user_id'])['order_number'].transform(np.max)

In [10]:
# Checking the results of the query / checking the new column. 

ords_prods_new_var.head(50)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,product_name,aisle_id,department_id,prices,opp_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,0.0,196,1,0,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2539329,1,prior,1,2,8,0.0,14084,2,0,...,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
2,2539329,1,prior,1,2,8,0.0,12427,3,0,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
3,2539329,1,prior,1,2,8,0.0,26088,4,0,...,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
4,2539329,1,prior,1,2,8,0.0,26405,5,0,...,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
5,2398795,1,prior,2,3,7,15.0,196,1,1,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Slowest two days,Average orders,10
6,2398795,1,prior,2,3,7,15.0,10258,2,0,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Slowest two days,Average orders,10
7,2398795,1,prior,2,3,7,15.0,12427,3,1,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Slowest two days,Average orders,10
8,2398795,1,prior,2,3,7,15.0,13176,4,0,...,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,Slowest two days,Average orders,10
9,2398795,1,prior,2,3,7,15.0,26088,5,1,...,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Slowest two days,Average orders,10
10,2398795,1,prior,2,3,7,15.0,13032,6,0,...,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,Slowest two days,Average orders,10
11,473747,1,prior,3,3,12,21.0,196,1,1,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Slowest two days,Most orders,10
12,473747,1,prior,3,3,12,21.0,12427,2,1,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Slowest two days,Most orders,10
13,473747,1,prior,3,3,12,21.0,10258,3,1,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Slowest two days,Most orders,10
14,473747,1,prior,3,3,12,21.0,25133,4,0,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Slowest two days,Most orders,10
15,473747,1,prior,3,3,12,21.0,30450,5,0,...,Creamy Almond Butter,88.0,13.0,3.2,both,Low-range product,Regularly busy,Slowest two days,Most orders,10
16,2254736,1,prior,4,4,7,29.0,196,1,1,...,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,Slowest two days,Average orders,10
17,2254736,1,prior,4,4,7,29.0,12427,2,1,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,Slowest two days,Average orders,10
18,2254736,1,prior,4,4,7,29.0,10258,3,1,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,Slowest two days,Average orders,10
19,2254736,1,prior,4,4,7,29.0,25133,4,1,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,Slowest two days,Average orders,10
20,2254736,1,prior,4,4,7,29.0,26405,5,1,...,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Least busy,Slowest two days,Average orders,10
21,431534,1,prior,5,4,15,28.0,196,1,1,...,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,Slowest two days,Most orders,10
22,431534,1,prior,5,4,15,28.0,12427,2,1,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,Slowest two days,Most orders,10
23,431534,1,prior,5,4,15,28.0,10258,3,1,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,Slowest two days,Most orders,10
24,431534,1,prior,5,4,15,28.0,25133,4,1,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,Slowest two days,Most orders,10
25,431534,1,prior,5,4,15,28.0,10326,5,0,...,Organic Fuji Apples,24.0,4.0,2.7,both,Low-range product,Least busy,Slowest two days,Most orders,10
26,431534,1,prior,5,4,15,28.0,17122,6,0,...,Honeycrisp Apples,24.0,4.0,14.0,both,Mid-range product,Least busy,Slowest two days,Most orders,10
27,431534,1,prior,5,4,15,28.0,41787,7,0,...,Bartlett Pears,24.0,4.0,5.0,both,Low-range product,Least busy,Slowest two days,Most orders,10
28,431534,1,prior,5,4,15,28.0,13176,8,1,...,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Least busy,Slowest two days,Most orders,10
29,3367565,1,prior,6,2,7,19.0,196,1,1,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
30,3367565,1,prior,6,2,7,19.0,12427,2,1,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
31,3367565,1,prior,6,2,7,19.0,10258,3,1,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
32,3367565,1,prior,6,2,7,19.0,25133,4,1,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
33,550135,1,prior,7,1,9,20.0,196,1,1,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest two days,Average orders,10
34,550135,1,prior,7,1,9,20.0,10258,2,1,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest two days,Average orders,10
35,550135,1,prior,7,1,9,20.0,12427,3,1,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest two days,Average orders,10
36,550135,1,prior,7,1,9,20.0,25133,4,1,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest two days,Average orders,10
37,550135,1,prior,7,1,9,20.0,13032,5,1,...,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,Busiest two days,Average orders,10
38,3108588,1,prior,8,1,14,14.0,12427,1,1,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest two days,Most orders,10
39,3108588,1,prior,8,1,14,14.0,196,2,1,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest two days,Most orders,10
40,3108588,1,prior,8,1,14,14.0,10258,3,1,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest two days,Most orders,10
41,3108588,1,prior,8,1,14,14.0,25133,4,1,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest two days,Most orders,10
42,3108588,1,prior,8,1,14,14.0,46149,5,0,...,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Regularly busy,Busiest two days,Most orders,10
43,3108588,1,prior,8,1,14,14.0,49235,6,0,...,Organic Half & Half,53.0,16.0,1.8,both,Low-range product,Regularly busy,Busiest two days,Most orders,10
44,2295261,1,prior,9,1,16,0.0,49235,1,1,...,Organic Half & Half,53.0,16.0,1.8,both,Low-range product,Regularly busy,Busiest two days,Average orders,10
45,2295261,1,prior,9,1,16,0.0,46149,2,1,...,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Regularly busy,Busiest two days,Average orders,10
46,2295261,1,prior,9,1,16,0.0,25133,3,1,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest two days,Average orders,10
47,2295261,1,prior,9,1,16,0.0,196,4,1,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest two days,Average orders,10
48,2295261,1,prior,9,1,16,0.0,10258,5,1,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest two days,Average orders,10
49,2295261,1,prior,9,1,16,0.0,12427,6,1,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest two days,Average orders,10

> Then I am creating the loyalty flags according to brief:

In [11]:
ords_prods_new_var.loc[ords_prods_new_var['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [12]:
ords_prods_new_var.loc[(ords_prods_new_var['max_order'] <= 40) & (ords_prods_new_var['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [13]:
ords_prods_new_var.loc[ords_prods_new_var['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [14]:
# Checking the results of the newly creating loyalty flags

ords_prods_new_var['loyalty_flag'].value_counts(dropna = False)

Regular customer    15891507
Loyal customer      10294027
New customer         6249525
Name: loyalty_flag, dtype: int64

In [15]:
# Checking the results of the query / checking the new column. 
# However here I chose to select only specific & relevant columns, instead of loading all of them. 

ords_prods_new_var[['user_id', 'loyalty_flag', 'order_number', 'max_order']].head(100)

    user_id      loyalty_flag  order_number  max_order
0         1      New customer             1         10
1         1      New customer             1         10
2         1      New customer             1         10
3         1      New customer             1         10
4         1      New customer             1         10
5         1      New customer             2         10
6         1      New customer             2         10
7         1      New customer             2         10
8         1      New customer             2         10
9         1      New customer             2         10
10        1      New customer             2         10
11        1      New customer             3         10
12        1      New customer             3         10
13        1      New customer             3         10
14        1      New customer             3         10
15        1      New customer             3         10
16        1      New customer             4         10
17        1      New customer             4         10
18        1      New customer             4         10
19        1      New customer             4         10
20        1      New customer             4         10
21        1      New customer             5         10
22        1      New customer             5         10
23        1      New customer             5         10
24        1      New customer             5         10
25        1      New customer             5         10
26        1      New customer             5         10
27        1      New customer             5         10
28        1      New customer             5         10
29        1      New customer             6         10
30        1      New customer             6         10
31        1      New customer             6         10
32        1      New customer             6         10
33        1      New customer             7         10
34        1      New customer             7         10
35        1      New customer             7         10
36        1      New customer             7         10
37        1      New customer             7         10
38        1      New customer             8         10
39        1      New customer             8         10
40        1      New customer             8         10
41        1      New customer             8         10
42        1      New customer             8         10
43        1      New customer             8         10
44        1      New customer             9         10
45        1      New customer             9         10
46        1      New customer             9         10
47        1      New customer             9         10
48        1      New customer             9         10
49        1      New customer             9         10
50        1      New customer            10         10
51        1      New customer            10         10
52        1      New customer            10         10
53        1      New customer            10         10
54        1      New customer            10         10
55        1      New customer            10         10
56        1      New customer            10         10
57        1      New customer            10         10
58        1      New customer            10         10
59        2  Regular customer             1         14
60        2  Regular customer             1         14
61        2  Regular customer             1         14
62        2  Regular customer             1         14
63        2  Regular customer             1         14
64        2  Regular customer             1         14
65        2  Regular customer             1         14
66        2  Regular customer             1         14
67        2  Regular customer             1         14
68        2  Regular customer             1         14
69        2  Regular customer             1         14
70        2  Regular customer             1         14
71        2  Regular customer             1         14
72        2  Regular customer             2         14
73        2  Regular customer             2         14
74        2  Regular customer             2         14
75        2  Regular customer             2         14
76        2  Regular customer             2         14
77        2  Regular customer             2         14
78        2  Regular customer             3         14
79        2  Regular customer             3         14
80        2  Regular customer             3         14
81        2  Regular customer             3         14
82        2  Regular customer             3         14
83        2  Regular customer             4         14
84        2  Regular customer             4         14
85        2  Regular customer             4         14
86        2  Regular customer             4         14
87        2  Regular customer             4         14
88        2  Regular customer             4         14
89        2  Regular customer             4         14
90        2  Regular customer             4         14
91        2  Regular customer             4         14
92        2  Regular customer             4         14
93        2  Regular customer             4         14
94        2  Regular customer             4         14
95        2  Regular customer             4         14
96        2  Regular customer             5         14
97        2  Regular customer             5         14
98        2  Regular customer             5         14
99        2  Regular customer             5         14

> ##### D5: The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [16]:
ords_prods_new_var.groupby('loyalty_flag').agg({'prices': ['count', 'mean', 'sum', 'min', 'max']})

                    prices
                     count       mean          sum  min      max
loyalty_flag
Loyal customer    10284093  10.386336  106814042.2  1.0  99999.0
New customer       6243990  13.294670   83011787.2  1.0  99999.0
Regular customer  15876776  12.495717  198391693.2  1.0  99999.0

> The above statistics showcase (1) the count of customers per flag, (2) the mean price paid per product purchased, (3) the total sum [gross profit] spent per customer group, (4) & (5) the minimum and maximum spent.

> Some early conclusions would be: (1) new customers buy more expensive products, (2) loyal customers buy cheaper products, (3) the most populated group is 'regular customer' (almost 16 millions).

> ##### D6: The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:

> - If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
> - If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [18]:
# The first step is to create a new variable to base my spending flag on. 

ords_prods_new_var['avg_spent'] = ords_prods_new_var.groupby(['user_id'])['prices'].transform(np.mean)

In [19]:
# Checking the results of the query / checking the new column. 

ords_prods_new_var[['user_id', 'order_number', 'prices', 'avg_spent']].tail(100)

          user_id  order_number  prices  avg_spent
32434959   206209             3     3.7   7.058915
32434960   206209             3     1.1   7.058915
32434961   206209             3     5.9   7.058915
32434962   206209             3     4.8   7.058915
32434963   206209             3     4.4   7.058915
32434964   206209             3    12.6   7.058915
32434965   206209             3     9.1   7.058915
32434966   206209             3     5.8   7.058915
32434967   206209             4     4.8   7.058915
32434968   206209             4    10.3   7.058915
32434969   206209             4     3.7   7.058915
32434970   206209             4     5.2   7.058915
32434971   206209             4     4.7   7.058915
32434972   206209             4     6.3   7.058915
32434973   206209             4     1.8   7.058915
32434974   206209             4     5.5   7.058915
32434975   206209             4    18.8   7.058915
32434976   206209             4     4.4   7.058915
32434977   206209             4    11.1   7.058915
32434978   206209             4     3.8   7.058915
32434979   206209             4     6.1   7.058915
32434980   206209             4     6.5   7.058915
32434981   206209             4     4.6   7.058915
32434982   206209             4     9.1   7.058915
32434983   206209             5    11.5   7.058915
32434984   206209             5    11.3   7.058915
32434985   206209             5    10.3   7.058915
32434986   206209             6     5.6   7.058915
32434987   206209             6     5.5   7.058915
32434988   206209             7    11.3   7.058915
32434989   206209             7    11.5   7.058915
32434990   206209             7     9.0   7.058915
32434991   206209             7     1.8   7.058915
32434992   206209             7     5.9   7.058915
32434993   206209             7     8.3   7.058915
32434994   206209             7     4.0   7.058915
32434995   206209             7     1.8   7.058915
32434996   206209             7     9.2   7.058915
32434997   206209             7    14.3   7.058915
32434998   206209             8     5.8   7.058915
32434999   206209             8     3.8   7.058915
32435000   206209             8     4.6   7.058915
32435001   206209             8    10.3   7.058915
32435002   206209             8    11.3   7.058915
32435003   206209             8     2.1   7.058915
32435004   206209             8    13.6   7.058915
32435005   206209             8    11.5   7.058915
32435006   206209             8     1.8   7.058915
32435007   206209             8     1.3   7.058915
32435008   206209             8     2.1   7.058915
32435009   206209             8     7.0   7.058915
32435010   206209             9     5.8   7.058915
32435011   206209             9     9.1   7.058915
32435012   206209             9    11.3   7.058915
32435013   206209            10    11.5   7.058915
32435014   206209            10    11.3   7.058915
32435015   206209            10     2.3   7.058915
32435016   206209            10     6.2   7.058915
32435017   206209            10     4.8   7.058915
32435018   206209            10     6.2   7.058915
32435019   206209            10    12.3   7.058915
32435020   206209            10     3.8   7.058915
32435021   206209            10     6.3   7.058915
32435022   206209            11    11.3   7.058915
32435023   206209            11    11.5   7.058915
32435024   206209            11     4.8   7.058915
32435025   206209            11    12.3   7.058915
32435026   206209            11     4.6   7.058915
32435027   206209            11     2.3   7.058915
32435028   206209            11     1.9   7.058915
32435029   206209            11     7.4   7.058915
32435030   206209            12    11.3   7.058915
32435031   206209            12    12.3   7.058915
32435032   206209            12    11.5   7.058915
32435033   206209            12     4.6   7.058915
32435034   206209            12     4.8   7.058915
32435035   206209            12     2.3   7.058915
32435036   206209            12     5.8   7.058915
32435037   206209            12    14.7   7.058915
32435038   206209            12     1.3   7.058915
32435039   206209            12     3.8   7.058915
32435040   206209            12     6.2   7.058915
32435041   206209            12     3.8   7.058915
32435042   206209            12     5.9   7.058915
32435043   206209            12     3.7   7.058915
32435044   206209            12     5.9   7.058915
32435045   206209            12    11.8   7.058915
32435046   206209            12     6.4   7.058915
32435047   206209            12     8.8   7.058915
32435048   206209            12     3.4   7.058915
32435049   206209            12     3.2   7.058915
32435050   206209            13    12.3   7.058915
32435051   206209            13    11.5   7.058915
32435052   206209            13    11.8   7.058915
32435053   206209            13     3.3   7.058915
32435054   206209            13     5.6   7.058915
32435055   206209            13     5.9   7.058915
32435056   206209            13     4.2   7.058915
32435057   206209            13     4.9   7.058915
32435058   206209            13     1.7   7.058915

> Now creating the flags according to brief:

In [20]:
ords_prods_new_var.loc[ords_prods_new_var['avg_spent'] < 10, 'spender_flag'] = 'Low spender'

In [21]:
ords_prods_new_var.loc[ords_prods_new_var['avg_spent'] >= 10, 'spender_flag'] = 'High spender'

In [22]:
# Checking the results

ords_prods_new_var[['user_id', 'order_number', 'prices', 'avg_spent', 'spender_flag']].head(100)

    user_id  order_number  prices  avg_spent spender_flag
0         1             1     9.0   6.367797  Low spender
1         1             1    12.5   6.367797  Low spender
2         1             1     4.4   6.367797  Low spender
3         1             1     4.7   6.367797  Low spender
4         1             1     1.0   6.367797  Low spender
5         1             2     9.0   6.367797  Low spender
6         1             2     3.0   6.367797  Low spender
7         1             2     4.4   6.367797  Low spender
8         1             2    10.3   6.367797  Low spender
9         1             2     4.7   6.367797  Low spender
10        1             2     4.0   6.367797  Low spender
11        1             3     9.0   6.367797  Low spender
12        1             3     4.4   6.367797  Low spender
13        1             3     3.0   6.367797  Low spender
14        1             3     8.6   6.367797  Low spender
15        1             3     3.2   6.367797  Low spender
16        1             4     9.0   6.367797  Low spender
17        1             4     4.4   6.367797  Low spender
18        1             4     3.0   6.367797  Low spender
19        1             4     8.6   6.367797  Low spender
20        1             4     1.0   6.367797  Low spender
21        1             5     9.0   6.367797  Low spender
22        1             5     4.4   6.367797  Low spender
23        1             5     3.0   6.367797  Low spender
24        1             5     8.6   6.367797  Low spender
25        1             5     2.7   6.367797  Low spender
26        1             5    14.0   6.367797  Low spender
27        1             5     5.0   6.367797  Low spender
28        1             5    10.3   6.367797  Low spender
29        1             6     9.0   6.367797  Low spender
30        1             6     4.4   6.367797  Low spender
31        1             6     3.0   6.367797  Low spender
32        1             6     8.6   6.367797  Low spender
33        1             7     9.0   6.367797  Low spender
34        1             7     3.0   6.367797  Low spender
35        1             7     4.4   6.367797  Low spender
36        1             7     8.6   6.367797  Low spender
37        1             7     4.0   6.367797  Low spender
38        1             8     4.4   6.367797  Low spender
39        1             8     9.0   6.367797  Low spender
40        1             8     3.0   6.367797  Low spender
41        1             8     8.6   6.367797  Low spender
42        1             8    13.4   6.367797  Low spender
43        1             8     1.8   6.367797  Low spender
44        1             9     1.8   6.367797  Low spender
45        1             9    13.4   6.367797  Low spender
46        1             9     8.6   6.367797  Low spender
47        1             9     9.0   6.367797  Low spender
48        1             9     3.0   6.367797  Low spender
49        1             9     4.4   6.367797  Low spender
50        1            10     9.0   6.367797  Low spender
51        1            10    13.4   6.367797  Low spender
52        1            10     6.8   6.367797  Low spender
53        1            10    12.6   6.367797  Low spender
54        1            10     8.6   6.367797  Low spender
55        1            10     3.0   6.367797  Low spender
56        1            10     1.3   6.367797  Low spender
57        1            10     4.0   6.367797  Low spender
58        1            10     4.4   6.367797  Low spender
59        2             1     5.2   7.515897  Low spender
60        2             1     6.3   7.515897  Low spender
61        2             1     2.3   7.515897  Low spender
62        2             1    10.9   7.515897  Low spender
63        2             1     2.7   7.515897  Low spender
64        2             1     4.1   7.515897  Low spender
65        2             1     5.0   7.515897  Low spender
66        2             1     9.4   7.515897  Low spender
67        2             1    14.8   7.515897  Low spender
68        2             1     7.5   7.515897  Low spender
69        2             1     4.4   7.515897  Low spender
70        2             1    10.3   7.515897  Low spender
71        2             1     2.5   7.515897  Low spender
72        2             2     1.3   7.515897  Low spender
73        2             2     2.0   7.515897  Low spender
74        2             2     3.5   7.515897  Low spender
75        2             2     6.3   7.515897  Low spender
76        2             2     3.9   7.515897  Low spender
77        2             2     2.0   7.515897  Low spender
78        2             3     6.3   7.515897  Low spender
79        2             3     5.2   7.515897  Low spender
80        2             3     2.3   7.515897  Low spender
81        2             3     6.6   7.515897  Low spender
82        2             3     6.2   7.515897  Low spender
83        2             4     7.1   7.515897  Low spender
84        2             4     5.2   7.515897  Low spender
85        2             4     7.5   7.515897  Low spender
86        2             4     5.8   7.515897  Low spender
87        2             4     8.9   7.515897  Low spender
88        2             4     9.1   7.515897  Low spender
89        2             4     5.5   7.515897  Low spender
90        2             4    12.3   7.515897  Low spender
91        2             4     4.0   7.515897  Low spender
92        2             4    10.8   7.515897  Low spender
93        2             4    12.6   7.515897  Low spender
94        2             4     2.0   7.515897  Low spender
95        2             4     5.9   7.515897  Low spender
96        2             5    14.0   7.515897  Low spender
97        2             5     2.9   7.515897  Low spender
98        2             5     1.6   7.515897  Low spender
99        2             5     3.4   7.515897  Low spender

> ##### D7: In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:
> - If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
> - If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
> - If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [23]:
# The first step is to create a new variable to base my order frequency flag on. 

ords_prods_new_var['median_order_freq'] = ords_prods_new_var.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [24]:
# Checking the results of the query / checking the new column. 

ords_prods_new_var[['user_id', 'order_number', 'days_since_prior_order', 'median_order_freq']].head(100)

    user_id  order_number  days_since_prior_order  median_order_freq
0         1             1                     0.0               20.0
1         1             1                     0.0               20.0
2         1             1                     0.0               20.0
3         1             1                     0.0               20.0
4         1             1                     0.0               20.0
5         1             2                    15.0               20.0
6         1             2                    15.0               20.0
7         1             2                    15.0               20.0
8         1             2                    15.0               20.0
9         1             2                    15.0               20.0
10        1             2                    15.0               20.0
11        1             3                    21.0               20.0
12        1             3                    21.0               20.0
13        1             3                    21.0               20.0
14        1             3                    21.0               20.0
15        1             3                    21.0               20.0
16        1             4                    29.0               20.0
17        1             4                    29.0               20.0
18        1             4                    29.0               20.0
19        1             4                    29.0               20.0
20        1             4                    29.0               20.0
21        1             5                    28.0               20.0
22        1             5                    28.0               20.0
23        1             5                    28.0               20.0
24        1             5                    28.0               20.0
25        1             5                    28.0               20.0
26        1             5                    28.0               20.0
27        1             5                    28.0               20.0
28        1             5                    28.0               20.0
29        1             6                    19.0               20.0
30        1             6                    19.0               20.0
31        1             6                    19.0               20.0
32        1             6                    19.0               20.0
33        1             7                    20.0               20.0
34        1             7                    20.0               20.0
35        1             7                    20.0               20.0
36        1             7                    20.0               20.0
37        1             7                    20.0               20.0
38        1             8                    14.0               20.0
39        1             8                    14.0               20.0
40        1             8                    14.0               20.0
41        1             8                    14.0               20.0
42        1             8                    14.0               20.0
43        1             8                    14.0               20.0
44        1             9                     0.0               20.0
45        1             9                     0.0               20.0
46        1             9                     0.0               20.0
47        1             9                     0.0               20.0
48        1             9                     0.0               20.0
49        1             9                     0.0               20.0
50        1            10                    30.0               20.0
51        1            10                    30.0               20.0
52        1            10                    30.0               20.0
53        1            10                    30.0               20.0
54        1            10                    30.0               20.0
55        1            10                    30.0               20.0
56        1            10                    30.0               20.0
57        1            10                    30.0               20.0
58        1            10                    30.0               20.0
59        2             1                     0.0               13.0
60        2             1                     0.0               13.0
61        2             1                     0.0               13.0
62        2             1                     0.0               13.0
63        2             1                     0.0               13.0
64        2             1                     0.0               13.0
65        2             1                     0.0               13.0
66        2             1                     0.0               13.0
67        2             1                     0.0               13.0
68        2             1                     0.0               13.0
69        2             1                     0.0               13.0
70        2             1                     0.0               13.0
71        2             1                     0.0               13.0
72        2             2                    10.0               13.0
73        2             2                    10.0               13.0
74        2             2                    10.0               13.0
75        2             2                    10.0               13.0
76        2             2                    10.0               13.0
77        2             2                    10.0               13.0
78        2             3                     3.0               13.0
79        2             3                     3.0               13.0
80        2             3                     3.0               13.0
81        2             3                     3.0               13.0
82        2             3                     3.0               13.0
83        2             4                     8.0               13.0
84        2             4                     8.0               13.0
85        2             4                     8.0               13.0
86        2             4                     8.0               13.0
87        2             4                     8.0               13.0
88        2             4                     8.0               13.0
89        2             4                     8.0               13.0
90        2             4                     8.0               13.0
91        2             4                     8.0               13.0
92        2             4                     8.0               13.0
93        2             4                     8.0               13.0
94        2             4                     8.0               13.0
95        2             4                     8.0               13.0
96        2             5                     8.0               13.0
97        2             5                     8.0               13.0
98        2             5                     8.0               13.0
99        2             5                     8.0               13.0

> Now creating the flags according to brief:

In [25]:
ords_prods_new_var.loc[ords_prods_new_var['median_order_freq'] > 20, 'order_freq_flag'] = 'Non-frequent customer'

In [26]:
ords_prods_new_var.loc[(ords_prods_new_var['median_order_freq'] > 10) & (ords_prods_new_var['median_order_freq'] <= 20), 'order_freq_flag'] = 'Regular customer'

In [27]:
ords_prods_new_var.loc[ords_prods_new_var['median_order_freq'] <= 10, 'order_freq_flag'] = 'Frequent customer'

In [28]:
# Checking the results

ords_prods_new_var[['user_id', 'order_number', 'days_since_prior_order', 'median_order_freq', 'order_freq_flag']].head(100)

,user_id,order_number,days_since_prior_order,median_order_freq,order_freq_flag
0,1,1,0.0,20.0,Regular customer
1,1,1,0.0,20.0,Regular customer
2,1,1,0.0,20.0,Regular customer
3,1,1,0.0,20.0,Regular customer
4,1,1,0.0,20.0,Regular customer
5,1,2,15.0,20.0,Regular customer
6,1,2,15.0,20.0,Regular customer
7,1,2,15.0,20.0,Regular customer
8,1,2,15.0,20.0,Regular customer
9,1,2,15.0,20.0,Regular customer
10,1,2,15.0,20.0,Regular customer
11,1,3,21.0,20.0,Regular customer
12,1,3,21.0,20.0,Regular customer
13,1,3,21.0,20.0,Regular customer
14,1,3,21.0,20.0,Regular customer
15,1,3,21.0,20.0,Regular customer
16,1,4,29.0,20.0,Regular customer
17,1,4,29.0,20.0,Regular customer
18,1,4,29.0,20.0,Regular customer
19,1,4,29.0,20.0,Regular customer
20,1,4,29.0,20.0,Regular customer
21,1,5,28.0,20.0,Regular customer
22,1,5,28.0,20.0,Regular customer
23,1,5,28.0,20.0,Regular customer
24,1,5,28.0,20.0,Regular customer
25,1,5,28.0,20.0,Regular customer
26,1,5,28.0,20.0,Regular customer
27,1,5,28.0,20.0,Regular customer
28,1,5,28.0,20.0,Regular customer
29,1,6,19.0,20.0,Regular customer
30,1,6,19.0,20.0,Regular customer
31,1,6,19.0,20.0,Regular customer
32,1,6,19.0,20.0,Regular customer
33,1,7,20.0,20.0,Regular customer
34,1,7,20.0,20.0,Regular customer
35,1,7,20.0,20.0,Regular customer
36,1,7,20.0,20.0,Regular customer
37,1,7,20.0,20.0,Regular customer
38,1,8,14.0,20.0,Regular customer
39,1,8,14.0,20.0,Regular customer
40,1,8,14.0,20.0,Regular customer
41,1,8,14.0,20.0,Regular customer
42,1,8,14.0,20.0,Regular customer
43,1,8,14.0,20.0,Regular customer
44,1,9,0.0,20.0,Regular customer
45,1,9,0.0,20.0,Regular customer
46,1,9,0.0,20.0,Regular customer
47,1,9,0.0,20.0,Regular customer
48,1,9,0.0,20.0,Regular customer
49,1,9,0.0,20.0,Regular customer
50,1,10,30.0,20.0,Regular customer
51,1,10,30.0,20.0,Regular customer
52,1,10,30.0,20.0,Regular customer
53,1,10,30.0,20.0,Regular customer
54,1,10,30.0,20.0,Regular customer
55,1,10,30.0,20.0,Regular customer
56,1,10,30.0,20.0,Regular customer
57,1,10,30.0,20.0,Regular customer
58,1,10,30.0,20.0,Regular customer
59,2,1,0.0,13.0,Regular customer
60,2,1,0.0,13.0,Regular customer
61,2,1,0.0,13.0,Regular customer
62,2,1,0.0,13.0,Regular customer
63,2,1,0.0,13.0,Regular customer
64,2,1,0.0,13.0,Regular customer
65,2,1,0.0,13.0,Regular customer
66,2,1,0.0,13.0,Regular customer
67,2,1,0.0,13.0,Regular customer
68,2,1,0.0,13.0,Regular customer
69,2,1,0.0,13.0,Regular customer
70,2,1,0.0,13.0,Regular customer
71,2,1,0.0,13.0,Regular customer
72,2,2,10.0,13.0,Regular customer
73,2,2,10.0,13.0,Regular customer
74,2,2,10.0,13.0,Regular customer
75,2,2,10.0,13.0,Regular customer
76,2,2,10.0,13.0,Regular customer
77,2,2,10.0,13.0,Regular customer
78,2,3,3.0,13.0,Regular customer
79,2,3,3.0,13.0,Regular customer
80,2,3,3.0,13.0,Regular customer
81,2,3,3.0,13.0,Regular customer
82,2,3,3.0,13.0,Regular customer
83,2,4,8.0,13.0,Regular customer
84,2,4,8.0,13.0,Regular customer
85,2,4,8.0,13.0,Regular customer
86,2,4,8.0,13.0,Regular customer
87,2,4,8.0,13.0,Regular customer
88,2,4,8.0,13.0,Regular customer
89,2,4,8.0,13.0,Regular customer
90,2,4,8.0,13.0,Regular customer
91,2,4,8.0,13.0,Regular customer
92,2,4,8.0,13.0,Regular customer
93,2,4,8.0,13.0,Regular customer
94,2,4,8.0,13.0,Regular customer
95,2,4,8.0,13.0,Regular customer
96,2,5,8.0,13.0,Regular customer
97,2,5,8.0,13.0,Regular customer
98,2,5,8.0,13.0,Regular customer
99,2,5,8.0,13.0,Regular customer

## 5. Final Checks

> ##### D8: Ensure your notebook is clean and structured and that your code is well commented.

In [29]:
ords_prods_new_var.head(10)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_spent,spender_flag,median_order_freq,order_freq_flag
0,2539329,1,prior,1,2,8,0.0,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
1,2539329,1,prior,1,2,8,0.0,14084,2,0,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
2,2539329,1,prior,1,2,8,0.0,12427,3,0,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
3,2539329,1,prior,1,2,8,0.0,26088,4,0,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
4,2539329,1,prior,1,2,8,0.0,26405,5,0,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
5,2398795,1,prior,2,3,7,15.0,196,1,1,...,Mid-range product,Regularly busy,Slowest two days,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
6,2398795,1,prior,2,3,7,15.0,10258,2,0,...,Low-range product,Regularly busy,Slowest two days,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
7,2398795,1,prior,2,3,7,15.0,12427,3,1,...,Low-range product,Regularly busy,Slowest two days,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
8,2398795,1,prior,2,3,7,15.0,13176,4,0,...,Mid-range product,Regularly busy,Slowest two days,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer
9,2398795,1,prior,2,3,7,15.0,26088,5,1,...,Low-range product,Regularly busy,Slowest two days,Average orders,10,New customer,6.367797,Low spender,20.0,Regular customer

In [30]:
ords_prods_new_var.tail(10)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_spent,spender_flag,median_order_freq,order_freq_flag
32435049,626363,206209,prior,12,1,12,18.0,14727,20,0,...,Low-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435050,2977660,206209,prior,13,1,12,7.0,24852,1,1,...,Mid-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435051,2977660,206209,prior,13,1,12,7.0,9405,2,1,...,Mid-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435052,2977660,206209,prior,13,1,12,7.0,16168,3,1,...,Mid-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435053,2977660,206209,prior,13,1,12,7.0,39216,4,0,...,Low-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435054,2977660,206209,prior,13,1,12,7.0,14197,5,1,...,Mid-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435055,2977660,206209,prior,13,1,12,7.0,38730,6,0,...,Mid-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435056,2977660,206209,prior,13,1,12,7.0,31477,7,0,...,Low-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435057,2977660,206209,prior,13,1,12,7.0,6567,8,0,...,Low-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer
32435058,2977660,206209,prior,13,1,12,7.0,22920,9,0,...,Low-range product,Regularly busy,Busiest two days,Most orders,13,Regular customer,7.058915,Low spender,18.0,Regular customer

In [31]:
ords_prods_new_var.shape

(32435059, 26)

## 6. Exporting Dataframe

> ##### D9: Export your dataframe as a pickle file and store it correctly in your “Prepared Data” folder.

In [32]:
ords_prods_new_var.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_group_agg.pkl'))